### ISSUE TITLE
Switch Task List 

### ISSUE THREAD

**Issue by krottmas** [chigc/software#17]
- [x] Download and transform to TEI
- [x] Check Data (dates, heights, widths) 
- [x] strip old data from Github
- [x] insetr info from Sciebo 
- [x] Framework Fix - Add field for origin; add field + Button for Former Shelfmarks (see CCC29); Add "altidentifier type= former ana=chigc:hasFormerIdentifier" - Mehrfachvergabe
